-- Copyright (c) Microsoft Corporation. All rights reserved.
-- Licensed under the PostgreSQL License.
--
-- Two-step check of the real keeper FSM (KeeperFSM[], src/bin/pg_autoctl/
-- fsm.c) against the monitor's own MonitorFSM[] table, using the
-- keeper_fsm_edges.json fixture committed alongside this file. That fixture
-- is generated from the real KeeperFSM[] via
-- "pg_autoctl inspect fsm list --json" (KeeperFSMToJSON(), fsm.c) -- see
-- cli_do_fsm_list's own comment for how that command runs with zero setup
-- (no --pgdata, no live cluster) -- and must be regenerated by hand
-- whenever KeeperFSM[] changes; this test only reads the fixture, it never
-- runs pg_autoctl itself.
--
-- Step 1: load the fixture client-side (psql's own backtick file
-- embedding, not server-side pg_read_file() -- the latter is
-- superuser/pg_read_server_files-gated and resolves relative paths against
-- $PGDATA, not this test's own directory) into a real table, one row per
-- distinct keeper edge, so this test's own expected/keeper_fsm_edges.out
-- shows the whole keeper FSM line by line, human-reviewable, with a diff on
-- every change to KeeperFSM[] -- the same discipline fsm.sql's own dump
-- already gives MonitorFSM[]. DISTINCT: KeeperFSMToJSON()'s ANY_STATE
-- expansion (see its own comment, fsm.c) can make two different
-- KeeperFSM[] rows resolve to the exact same (current, assigned) pair --
-- the JSON has no per-row provenance to tell such duplicates apart by, so
-- they carry no extra information here and would only clutter the
-- reviewable list.
\set keeper_json `cat keeper_fsm_edges.json`

CREATE TABLE keeper_fsm_edges AS
SELECT DISTINCT
       (edge ->> 'current')::pgautofailover.replication_state AS current_state,
       (edge ->> 'assigned')::pgautofailover.replication_state AS assigned_state
  FROM jsonb_array_elements(:'keeper_json'::jsonb) AS edge;

SELECT * FROM keeper_fsm_edges ORDER BY current_state, assigned_state;

-- Step 2a: monitor -> keeper direction -- every pgautofailover.dump_fsm_edges()
-- edge the keeper_fsm_edges table above has no matching row for. A
-- non-empty result here is a real, actionable gap (unlike
-- check_fsm_reachability.sql's own synthetic-input test, which only
-- exercises the comparison mechanism itself, not real data): see this
-- project's own investigation of these mismatches (dump_fsm_edges()'s own
-- comment, group_state_machine.c, and the design doc) for which of them
-- are genuine keeper gaps versus artifacts already excluded upstream.
SELECT e.pos, e.current_state, e.assigned_state, f.comment
  FROM pgautofailover.dump_fsm_edges() e
  JOIN pgautofailover.fsm f ON f.pos = e.pos
 WHERE NOT EXISTS (
         SELECT 1
           FROM keeper_fsm_edges k
          WHERE k.current_state = e.current_state
            AND k.assigned_state = e.assigned_state
       )
 ORDER BY e.pos, e.current_state;

-- Step 2b: keeper -> monitor direction, the reverse gap -- every keeper
-- edge that no MonitorFSM[] row can ever produce (dump_fsm_edges() is the
-- full, fully-resolved edge set the monitor's table can reach, see its own
-- comment). A non-empty result here means the keeper is prepared to
-- transition through a (current, assigned) pair the monitor itself would
-- never assign -- either genuinely dead keeper code, or a real coverage
-- gap on the monitor side, same "investigate before assuming which" caveat
-- as step 2a's own comment.
SELECT k.current_state, k.assigned_state
  FROM keeper_fsm_edges k
 WHERE NOT EXISTS (
         SELECT 1
           FROM pgautofailover.dump_fsm_edges() e
          WHERE e.current_state = k.current_state
            AND e.assigned_state = k.assigned_state
       )
 ORDER BY k.current_state, k.assigned_state;

DROP TABLE keeper_fsm_edges;
