-- Copyright (c) Microsoft Corporation. All rights reserved.
-- Licensed under the PostgreSQL License.
--
-- Two-step check of the real keeper FSM (KeeperFSM[], src/bin/pg_autoctl/
-- fsm.c) against the monitor's own MonitorFSM[] table, using the
-- keeper_fsm_edges.json fixture committed alongside this file. That fixture
-- is generated from the real KeeperFSM[] via
-- "pg_autoctl inspect fsm list --json" (KeeperFSMToJSON(), fsm.c) -- see
-- cli_do_fsm_list's own comment for how that command runs with zero setup
-- (no --pgdata, no live cluster) -- and must be regenerated by hand
-- whenever KeeperFSM[] changes; this test only reads the fixture, it never
-- runs pg_autoctl itself.
--
-- Step 1: load the fixture client-side (psql's own backtick file
-- embedding, not server-side pg_read_file() -- the latter is
-- superuser/pg_read_server_files-gated and resolves relative paths against
-- $PGDATA, not this test's own directory) into a real table, one row per
-- distinct keeper edge, so this test's own expected/keeper_fsm_edges.out
-- shows the whole keeper FSM line by line, human-reviewable, with a diff on
-- every change to KeeperFSM[] -- the same discipline fsm.sql's own dump
-- already gives MonitorFSM[].
--
-- current_state is plain text, not pgautofailover.replication_state: a row
-- whose real KeeperFSM[] .current is ANY_STATE (state_matches()'s wildcard)
-- is serialized by KeeperFSMToJSON() as the literal string "any" (see its
-- own comment, fsm.c), which is not a legal enum value by design -- it's a
-- sentinel Step 2a/2b below match structurally, not a real reported state.
-- Every other value is still round-tripped through the enum (CASE ... ELSE
-- ... ::pgautofailover.replication_state ... END) so a typo'd or unrecognized
-- state name in the fixture still fails loudly here, same as
-- check_fsm_reachability()'s own cast does for the live-cluster path.
--
-- DISTINCT: nothing in KeeperFSM[] guarantees two different rows can't
-- resolve to the exact same (current, assigned) pair, and the JSON has no
-- per-row provenance to tell such duplicates apart by, so they carry no
-- extra information here and would only clutter the reviewable list.
\set keeper_json `cat keeper_fsm_edges.json`

CREATE TABLE keeper_fsm_edges AS
SELECT DISTINCT
       CASE WHEN (edge ->> 'current') = 'any'
            THEN 'any'
            ELSE ((edge ->> 'current')::pgautofailover.replication_state)::text
       END AS current_state,
       (edge ->> 'assigned')::pgautofailover.replication_state AS assigned_state
  FROM jsonb_array_elements(:'keeper_json'::jsonb) AS edge;

SELECT * FROM keeper_fsm_edges ORDER BY current_state, assigned_state;

-- Step 2a: monitor -> keeper direction -- every pgautofailover.dump_fsm_edges()
-- edge the keeper_fsm_edges table above has no matching row for. A
-- non-empty result here is a real, actionable gap (unlike
-- check_fsm_reachability.sql's own synthetic-input test, which only
-- exercises the comparison mechanism itself, not real data): see this
-- project's own investigation of these mismatches (dump_fsm_edges()'s own
-- comment, group_state_machine.c, and the design doc) for which of them
-- are genuine keeper gaps versus artifacts already excluded upstream.
--
-- k.current_state = 'any' matches every e.current_state -- a keeper row
-- covering every current state also covers this specific one, so it counts
-- as a match here exactly like a literal (e.current_state, e.assigned_state)
-- row would.
--
-- GROUPING SETS adds one summary row per rule (pos, assigned_state, comment)
-- -- current_state NULL, n = how many current_states that single
-- MonitorFSM[] rule fans out to -- alongside the ordinary per-current_state
-- detail rows, so a rule using a broad NodeStatePattern (matching many
-- states at once) is immediately visible as one big number instead of
-- having to count its own detail rows by hand. NULLS FIRST puts each rule's
-- summary row right before its own detail rows, as a header.
--
-- As of this writing the gap list is exactly 10 rules this way (134 detail
-- rows total), each an "alone in group"/failover/Citus-worker rule whose
-- NodeStatePattern is a role or predicate check (e.g. !IsCurrentState(...),
-- an opaque NodeIsXxx() helper, or no state restriction at all) rather than
-- an enumerated state list -- investigated rule by rule against the
-- pre-refactor hand-written code (commit 9c9c9b9^): in every one of the 10,
-- that breadth already existed before this refactor (this is a faithful,
-- behavior-preserving translation, not a widening introduced here). Real
-- regression/tap-spec precedent exists for the "obvious" current_state each
-- rule is clearly meant for (e.g. issue #997 for pos 303, issue #1168 for
-- pos 325/347/349's sibling branches), but none of the 10 has a test
-- exercising the transition from one of the other, more exotic fanned-out
-- current_states (dropped, fast_forward, join_secondary, and similar) --
-- this is Step 2a's own structural artifact of enumerating a role/predicate
-- gate across every syntactically possible current_state, not a sign of 10
-- separate functional bugs.
--
-- Follow-up investigation of pos 209/211/325's own remaining gap states
-- (after wait_maintenance and wait_standby were resolved -- see
-- group_state_machine.c's reportedIsWaitStandby field (NodeStatusPattern)
-- and KeeperFSM[]'s new WAIT_MAINTENANCE_STATE rows, fsm.c):
--
--   * pos 209/211's fast_forward current_state is now genuinely fixed and
--     covered: a lone node reporting fast_forward (its WAL-source peer and
--     the old primary both gone mid MS-failover) now has matching
--     KeeperFSM[] rows (FAST_FORWARD_STATE -> SINGLE_STATE /
--     REPORT_LSN_STATE, fsm.c, reusing fsm_promote_standby/fsm_report_lsn
--     exactly like every other converged-standby source state) and real
--     pgaftest coverage (keeper_fsm_gap_candidate_fast_forward_left_alone.pgaf,
--     keeper_fsm_gap_priority_zero_fast_forward_left_alone.pgaf) reproducing
--     a genuine MS-failover candidate falling behind, fetching real WAL, and
--     then being left alone -- see those specs' own headers for why
--     node1/node2 must be removed from the group while node3 is still
--     fetching (not after it reports fast_forward) to actually exercise
--     these rows instead of racing against the monitor's own cascade
--     continuation.
--   * pos 209's join_secondary and prepare_maintenance current_states are no
--     longer even in this gap list at all: both were found to be a genuine
--     data-loss risk, not a missing convenience -- promoting either straight
--     to SINGLE if left alone can silently discard writes a *different,
--     already-promoted* primary made in the meantime (join_secondary: that
--     new primary already exists by the time this node reaches
--     join_secondary; prepare_maintenance: pos 343 lets the candidate
--     standby reach primary the moment this node's own reportedState merely
--     converges to prepare_maintenance, no removal required). Fixed by
--     excluding both from pos 209 itself (reportedIsJoinSecondary,
--     reportedIsPrepareMaintenance on NodeMatchesPattern) rather than adding
--     KeeperFSM[] rows -- there is nothing safe to promote either one to.
--     prepare_maintenance additionally needed a new no-op row (pos 208):
--     unlike join_secondary (already recognized by node_metadata.c's
--     IsParticipatingInPromotion, so a lone node there safely no-ops on its
--     own), a lone prepare_maintenance node isn't recognized by that
--     function, IsBeingPromoted, or IsInPrimaryState, so excluding it from
--     pos 209 alone would have left ProceedGroupStateFromContext's own
--     "couldn't find the primary node" guard to ereport(ERROR) on every
--     single subsequent heartbeat -- worse than the original bug. Both
--     fixes verified live: keeper_fsm_gap_primary_left_alone_mid_maintenance_handoff.pgaf
--     reproduces a lone prepare_maintenance primary staying safely parked
--     (goalstate never becomes single) and confirms it keeps successfully
--     checking in (reporttime advancing) rather than looping on that error.
--   * pos 211's own join_secondary/prepare_promotion/demote_timeout
--     current_states are now genuinely fixed and covered too, via a much
--     simpler path than pos 209's: report_lsn never grants write access, so
--     none of pos 209's split-brain argument carries over here -- there was
--     nothing *unsafe* about these, they were simply missing KeeperFSM[]
--     rows, the exact same shape of gap fast_forward had. All three reuse
--     fsm_report_lsn directly:
--       - prepare_promotion: entering it (fsm_prepare_standby_for_promotion)
--         is a no-op -- Postgres is untouched, still an ordinary streaming
--         standby -- so this is exactly as safe as SECONDARY/CATCHINGUP's
--         own existing rows.
--       - demote_timeout: fsm_stop_replication already sets
--         default_transaction_read_only=on before this state is ever
--         reported, so no writes can have landed here that a real primary
--         elsewhere wouldn't also already have.
--       - join_secondary: Postgres was cleanly checkpointed and stopped
--         (fsm_checkpoint_and_stop_postgres) before reaching this state --
--         a trustworthy, consistent copy of data that hasn't been
--         superseded by anything (unlike pos 209's own join_secondary
--         concern, there is no new primary for this data to have fallen
--         behind, since candidatePriority=0 was never in the running to
--         become one).
--     fsm_report_lsn's own restart (standby_restart_with_current_
--     replication_source, primary_standby.c) handles all three uniformly:
--     it stops Postgres if running, rewrites the recovery config with no
--     primary_conninfo, and restarts -- it never needs to reach any peer,
--     so it doesn't matter that none exist.
--
--     Verified via this test (Step 1/2a, the keeper_fsm_edges.json fixture
--     and dump_fsm_edges() both resolving these three edges consistently),
--     the code reasoning above, AND real live pgaftest reproduction for all
--     three (keeper_fsm_gap_priority_zero_candidate_left_alone_mid_promotion.pgaf,
--     keeper_fsm_gap_priority_zero_primary_left_alone_mid_demotion.pgaf,
--     keeper_fsm_gap_priority_zero_losing_candidate_left_alone_mid_handoff.pgaf).
--     A first attempt at live reproduction (an earlier session) found
--     exactly the race fast_forward's own fix doesn't have: fsm_prepare_
--     standby_for_promotion is a no-op, so the monitor's cascade advances
--     from assigned=prepare_promotion straight through to stop_replication
--     within the same heartbeat, before any external test script's own
--     "remove the other peers" SQL call can land in between. (That same
--     attempt did incidentally confirm live that stop_replication really
--     is a dead end below: node3 sat reporting stop_replication, endlessly
--     reassigned report_lsn by this same pos 211 row, with no KeeperFSM[]
--     row able to reach it.)
--
--     Step mode (PG_AUTOCTL_STEP_MODE, src/bin/pg_autoctl/step_socket.c)
--     removes that race entirely: a "no-autopilot" node's node-active
--     service never ticks on its own, so a pgaftest spec can drive it to
--     converge locally to prepare_promotion/demote_timeout/join_secondary
--     via one explicit "fsm step <node>" (see fsm_step_cmd,
--     src/bin/pgaftest/test_spec_parse.y) and then simply not issue the
--     next one for as long as it likes -- there is no cascade to race
--     against, because nothing happens without an explicit command. Once
--     frozen there, unreported to the monitor, each spec zeroes the node's
--     own candidate priority and force-removes its former peers, then a
--     single further "fsm step" reports the frozen state, receives the
--     newly-applicable report_lsn assignment from pos 211, and performs
--     the transition under test in the very same call. See those three
--     specs' own headers for the full mechanics, including why each one's
--     particular current_state needs a different cluster shape to reach in
--     the first place (a lone standby for prepare_promotion, the original
--     primary itself for demote_timeout, and a losing MS-failover
--     candidate for join_secondary).
--   * pos 211's stop_replication current_state is the one exception left
--     unfixed, and unlike the three above it is not simply "missing a row":
--     fsm_stop_replication doesn't just stop a process, its own comment
--     says it shuts down the replication stream "by promoting the
--     replica" -- Postgres has already left recovery onto a new timeline
--     by the time this state is reported. Getting back to an ordinary,
--     disconnected-standby report_lsn state from there needs a real
--     pg_rewind/basebackup style re-sync (fsm_restart_standby ->
--     fsm_rewind_or_init, already used for MAINTENANCE_STATE/
--     PREPARE_MAINTENANCE_STATE -> CATCHINGUP_STATE), and that function's
--     own first step, keeper_get_primary(), hard-requires a live,
--     reachable primary to rewind against or basebackup from -- which
--     cannot exist by pos 211's own "alone in group" precondition. No
--     existing function can do this safely when truly alone; left as a
--     documented, unfixed gap.
--   * pos 325's remaining "single" state (the primaryNode side) is a
--     genuine model contradiction, not just a contrived scenario: it would
--     require the primary to report goalState == reportedState == single
--     while a *separate* node in the same group is simultaneously converged
--     and reporting secondary -- but the instant a second node registers,
--     the primary's own goal moves off single (to wait_primary) as part of
--     that registration, before the joining node could ever reach
--     secondary. No real sequence of monitor/keeper actions can produce
--     this combination.
SELECT e.pos AS rule, count(*) AS n, e.current_state, e.assigned_state, f.comment
  FROM pgautofailover.dump_fsm_edges() e
  JOIN pgautofailover.fsm f ON f.pos = e.pos
 WHERE NOT EXISTS (
         SELECT 1
           FROM keeper_fsm_edges k
          WHERE k.assigned_state = e.assigned_state
            AND (k.current_state = 'any' OR k.current_state = e.current_state::text)
       )
 GROUP BY GROUPING SETS (
           (e.pos, e.assigned_state, f.comment, e.current_state),
           (e.pos, e.assigned_state, f.comment)
         )
 ORDER BY e.pos, e.assigned_state, e.current_state NULLS FIRST;

-- Step 2b: keeper -> monitor direction, the reverse gap -- every keeper
-- edge that no MonitorFSM[] row can ever produce (dump_fsm_edges() is the
-- full, fully-resolved edge set the monitor's table can reach, see its own
-- comment). A non-empty result here means the keeper is prepared to
-- transition through a (current, assigned) pair the monitor itself would
-- never assign -- either genuinely dead keeper code, or a real coverage
-- gap on the monitor side, same "investigate before assuming which" caveat
-- as step 2a's own comment.
--
-- For a k.current_state = 'any' row, "matches" is existential: at least one
-- current_state for which the monitor assigns this same target is enough
-- to say the target is implementable at all, so a gap here means the
-- monitor can NEVER produce this assigned_state from ANY current state --
-- e.g. "any -> dropped": KeeperFSM[]'s two ANY_STATE -> DROPPED rows
-- collapse to this single row (see Step 1's own comment on why "any" isn't
-- expanded per-state anymore -- the previous per-state expansion turned
-- this one keeper rule into 21 separate flagged rows here, a lot of
-- redundant noise for a single underlying fact), and it stays flagged
-- because dump_fsm_edges() really can never produce a 'dropped' edge at
-- all: the monitor's own equivalent (remove_node(), pos 101/103) lives
-- entirely in the api_triggered section, which dump_fsm_edges()
-- deliberately excludes (see its own comment) since those rows resolve
-- their target via hand-written C, not a NodeStatePattern. Same
-- "investigate before assuming which" caveat as the rest of this file
-- applies to every row below, "any" or not.
SELECT k.current_state, k.assigned_state
  FROM keeper_fsm_edges k
 WHERE NOT EXISTS (
         SELECT 1
           FROM pgautofailover.dump_fsm_edges() e
          WHERE e.assigned_state = k.assigned_state
            AND (k.current_state = 'any' OR k.current_state = e.current_state::text)
       )
 ORDER BY k.current_state, k.assigned_state;

DROP TABLE keeper_fsm_edges;
