version: "3.9"  # optional since v1.27.0

x-coord: &coordinator
  image: pg_auto_failover:cluster
  environment:
    PGDATA: /tmp/pgaf
    PGUSER: citus
    PGDATABASE: citus
    PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
  expose:
    - 5432
  command: |
    pg_autoctl create coordinator --ssl-self-signed --auth trust --pg-hba-lan --run

x-worker: &worker
  image: pg_auto_failover:cluster
  environment:
    PGDATA: /tmp/pgaf
    PGUSER: citus
    PGDATABASE: citus
    PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
  expose:
    - 5432
  command: |
    pg_autoctl create worker --ssl-self-signed --auth trust --pg-hba-lan --run

services:

  monitor:
    image: pg_auto_failover:cluster
    environment:
      PGDATA: /tmp/pgaf
      PG_AUTOCTL_DEBUG: 1
    command: |
      pg_autoctl create monitor --ssl-self-signed --auth trust --run
    expose:
      - 5432

  coord0a:
    <<: *coordinator
    hostname: coord0a

  coord0b:
    <<: *coordinator
    hostname: coord0b

  worker1a:
    <<: *worker
    hostname: worker1a
    command: |
      pg_autoctl create worker --group 1 --ssl-self-signed --auth trust --pg-hba-lan --run

  worker1b:
    <<: *worker
    hostname: worker1b
    command: |
      pg_autoctl create worker --group 1 --ssl-self-signed --auth trust --pg-hba-lan --run

  worker2a:
    <<: *worker
    hostname: worker2a
    command: |
      pg_autoctl create worker --group 2 --ssl-self-signed --auth trust --pg-hba-lan --run

  worker2b:
    <<: *worker
    hostname: worker2b
    command: |
      pg_autoctl create worker --group 2 --ssl-self-signed --auth trust --pg-hba-lan --run

  worker3a:
    <<: *worker
    hostname: worker3a
    command: |
      pg_autoctl create worker --group 3 --ssl-self-signed --auth trust --pg-hba-lan --run

  worker3b:
    <<: *worker
    hostname: worker3b
    command: |
      pg_autoctl create worker --group 3 --ssl-self-signed --auth trust --pg-hba-lan --run
