version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# declare the Python requirements to build the documentation
python:
  install:
    - requirements: docs/requirements.txt
