import pgautofailover_utils as pgautofailover
from nose.tools import *

import subprocess
import os, os.path, time, shutil

cluster = None
node1 = None
node2 = None

def setup_module():
    global cluster
    cluster = pgautofailover.Cluster()

def teardown_module():
    cluster.destroy()

def test_000_create_monitor():
    monitor = cluster.create_monitor("/tmp/skip/monitor", authMethod="skip")
    monitor.wait_until_pg_is_running()

    with open(os.path.join("/tmp/skip/monitor", "pg_hba.conf"), 'a') as hba:
        hba.write("host all all %s trust\n" % cluster.networkSubnet)

    monitor.reload_postgres()

def test_001_init_primary():
    global node1
    node1_path = cluster.pg_createcluster("node1")

    # make a copy of the debian's HBA file
    hba_path = os.path.join("/etc",
                            "/".join(node1_path.split("/")[3:]),
                            "pg_hba.conf")
    shutil.copyfile(hba_path, "/tmp/pg_hba.debian.conf")

    node1 = cluster.create_datanode(node1_path,
                                    authMethod="skip",
                                    listen_flag=True)
    node1.create()

    #
    # Check that we didn't edit the HBA file, thanks to --skip-pg-hba, here
    # in the test file spelled the strange way --auth skip.
    #
    # Thing is, in the test environment, we don't allow Postgres to listen
    # on "localhost", and we don't use Unix Domain Sockets (because we have
    # a single file-system and all servers are listening on the same port),
    # so we have to introduce two new rules in the HBA file.
    #
    # So we make a diff and ignore those two lines we know we had to add to
    # the HBA rules even though we're using --skip-pg-hba.
    #
    test_hba_line_node = \
        "host all all %s/32 trust # Auto-generated by pg_auto_failover" % \
        node1.vnode.address
    test_hba_line_network = \
        "host all all %s trust # Auto-generated by pg_auto_failover" % \
        cluster.networkSubnet

    p = subprocess.run(["diff",
                        "--ignore-matching-lines", test_hba_line_node,
                        "--ignore-matching-lines", test_hba_line_network,
                        "/tmp/pg_hba.debian.conf",
                        os.path.join(node1_path, "pg_hba.conf")],
                       text=True,
                       capture_output=True)

    print("diff %s <test env hba rules> %s %s" \
          % (p.args[1], p.args[5], p.args[6]))

    if p.returncode != 0:
        print("%s" % p.stdout)

    assert(p.returncode == 0)

    with open(os.path.join(node1_path, "pg_hba.conf"), 'a') as hba:
        # node1.run_sql_query will need
        # host "172.27.1.1", user "docker", database "postgres"
        hba.write("host postgres docker %s trust\n" % cluster.networkSubnet)
        hba.write("host all all %s trust\n" % cluster.networkSubnet)
        hba.write("host replication all %s trust\n" % cluster.networkSubnet)

    node1.reload_postgres()

    node1.run()
    assert node1.wait_until_state(target_state="single")

def test_002_create_t1():
    node1.run_sql_query("CREATE TABLE t1(a int)")
    node1.run_sql_query("INSERT INTO t1 VALUES (1), (2)")

def test_003_init_secondary():
    global node2
    node2 = cluster.create_datanode("/tmp/skip/node2",
                                    authMethod="skip",
                                    listen_flag=True)
    node2.create()

    with open(os.path.join("/tmp/skip/node2", "pg_hba.conf"), 'a') as hba:
        hba.write("host all all %s trust\n" % cluster.networkSubnet)
        hba.write("host replication all %s trust\n" % cluster.networkSubnet)

    node2.reload_postgres()

    node2.run()
    assert node2.wait_until_state(target_state="secondary")
    assert node1.wait_until_state(target_state="primary")

def test_004_failover():
    print()
    print("Calling pgautofailover.failover() on the monitor")
    cluster.monitor.failover()
    assert node2.wait_until_state(target_state="primary")
    assert node1.wait_until_state(target_state="secondary")
