services:

  monitor:
    image: pg_auto_failover:citus
    volumes:
      - /tmp/pgaf
      - ./ini/monitor.ini:/etc/pgaf/node.ini:ro
    expose:
      - 5432
    command: pg_autoctl node run

  coord:
    image: pg_auto_failover:citus
    volumes:
      - /tmp/pgaf
      - ./ini/coordinator.ini:/etc/pgaf/node.ini:ro
    environment:
      PGUSER: citus
      PGDATABASE: citus
    expose:
      - 5432
    command: pg_autoctl node run

  worker:
    image: pg_auto_failover:citus
    volumes:
      - /tmp/pgaf
      - ./ini/worker.ini:/etc/pgaf/node.ini:ro
    environment:
      PGUSER: citus
      PGDATABASE: citus
    expose:
      - 5432
    command: pg_autoctl node run
