version: "3.9"  # optional since v1.27.0

services:

  monitor:
    image: pg_auto_failover:citus
    environment:
      PGDATA: /tmp/pgaf
    command: |
      pg_autoctl create monitor --ssl-self-signed --auth trust --run
    expose:
      - 5432

  coord:
    image: pg_auto_failover:citus
    environment:
      PGDATA: /tmp/pgaf
      PGUSER: citus
      PGDATABASE: citus
      PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
    expose:
      - 5432
    command: |
      pg_autoctl create coordinator --ssl-self-signed --auth trust --pg-hba-lan --run

  worker:
    image: pg_auto_failover:citus
    environment:
      PGDATA: /tmp/pgaf
      PGUSER: citus
      PGDATABASE: citus
      PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
    expose:
     - 5432
    command: |
      pg_autoctl create worker --ssl-self-signed --auth trust --pg-hba-lan --run
