x-coord: &coordinator
  image: pg_auto_failover:citus
  volumes:
    - /tmp/pgaf
    - ./ini/coordinator.ini:/etc/pgaf/node.ini:ro
  environment:
    PGUSER: citus
    PGDATABASE: citus
  expose:
    - 5432
  command: pg_autoctl node run

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      PGUSER: citus
      PGDATABASE: citus
      PGHOST: coord0a,coord0b
      PGPORT: 5432
      PGAPPNAME: demo
      PGSSLMODE: require
      PGTARGETSESSIONATTRS: read-write

  monitor:
    image: pg_auto_failover:citus
    volumes:
      - /tmp/pgaf
      - ./ini/monitor.ini:/etc/pgaf/node.ini:ro
    expose:
      - 5432
    command: pg_autoctl node run

  coord0a:
    <<: *coordinator
    hostname: coord0a

  coord0b:
    <<: *coordinator
    hostname: coord0b

  worker1a:
    <<: &worker1
      image: pg_auto_failover:citus
      volumes:
        - /tmp/pgaf
        - ./ini/worker1.ini:/etc/pgaf/node.ini:ro
      environment:
        PGUSER: citus
        PGDATABASE: citus
      expose:
        - 5432
      command: pg_autoctl node run
    hostname: worker1a

  worker1b:
    <<: *worker1
    hostname: worker1b

  worker2a:
    <<: &worker2
      image: pg_auto_failover:citus
      volumes:
        - /tmp/pgaf
        - ./ini/worker2.ini:/etc/pgaf/node.ini:ro
      environment:
        PGUSER: citus
        PGDATABASE: citus
      expose:
        - 5432
      command: pg_autoctl node run
    hostname: worker2a

  worker2b:
    <<: *worker2
    hostname: worker2b

  worker3a:
    <<: &worker3
      image: pg_auto_failover:citus
      volumes:
        - /tmp/pgaf
        - ./ini/worker3.ini:/etc/pgaf/node.ini:ro
      environment:
        PGUSER: citus
        PGDATABASE: citus
      expose:
        - 5432
      command: pg_autoctl node run
    hostname: worker3a

  worker3b:
    <<: *worker3
    hostname: worker3b
