name: Continuous Integration

on:
  pull_request:
    branches:
    - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  run_tests:
    name: Run test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PGVERSION:
          - 11
          - 12
          - 13
          - 14
          - 15
          # - 16 # FIXME pg16 should be supported but main still does not work with it.
        TEST:
          - multi
          - single
          - monitor
          - ssl
          - citus
        include:
          - PGVERSION: 14
            TEST: tablespaces
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
            echo "PGVERSION=${{ matrix.PGVERSION }}" >> $GITHUB_ENV
            echo "TEST=${{ matrix.TEST }}" >> $GITHUB_ENV
            echo "TRAVIS_BUILD_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Build Docker Test Image
        run: |
          make build-test-image

      - name: Run Test
        timeout-minutes: 15
        run: |
          make ci-test
