name: Build docs

env:
  context:      /docs
  sphinx_image: hapostgres/sphinx-citus:latest

on:
  pull_request:
    branches:
    - main
    paths:
      - 'docs/**'
      - '!docs/tikz/**'
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  docs:
    name: Build sphinx html
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build hapostgres/sphinx-citus docker image
        uses: docker/build-push-action@v5
        with:
          context: ".${{ env.context }}"
          load: true
          tags: ${{ env.sphinx_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build docs with sphinx
        run: "docker run --rm -v .${{ env.context }}:/docs ${{ env.sphinx_image }} make html"
