name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  style_checker:
    name: Style check
    runs-on: ubuntu-latest
    container: citus/stylechecker:no-py
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set safe directory for git
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Check C formatting
        run: citus_indent --check

      - name: Check banned functions
        run: ci/banned.h.sh

  run_tests:
    name: Run test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PGVERSION:
          - 14
          - 15
          - 16
          - 17
        TEST:
          - multi
          - single
          - monitor
          - ssl
          - citus
        include:
          - PGVERSION: 14
            TEST: tablespaces
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set environment variables
        run: |
          echo "PGVERSION=${{ matrix.PGVERSION }}" >> $GITHUB_ENV
          echo "TEST=${{ matrix.TEST }}" >> $GITHUB_ENV
          echo "TRAVIS_BUILD_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Build Docker Test Image
        run: make build-test-image

      - name: Run Test
        timeout-minutes: 15
        run: make ci-test
