x-node: &node
  build:
    context: ../..
    dockerfile: Dockerfile
    tags:
      - pg_auto_failover:tutorial
  volumes:
    - /var/lib/postgres
    - ./ini/postgres.ini:/etc/pgaf/node.ini:ro
  environment:
    PGUSER: tutorial
    PGDATABASE: tutorial
  expose:
    - 5432
  command: pg_autoctl node run

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      PGUSER: tutorial
      PGDATABASE: tutorial
      PGHOST: node1,node2
      PGPORT: 5432
      PGAPPNAME: tutorial
      PGSSLMODE: require
      PGTARGETSESSIONATTRS: read-write

  monitor:
    image: pg_auto_failover:tutorial
    volumes:
      - /var/lib/postgres
      - ./ini/monitor.ini:/etc/pgaf/node.ini:ro
    expose:
      - 5432
    command: pg_autoctl node run

  node1:
    <<: *node
    hostname: node1

  node2:
    <<: *node
    hostname: node2

  node3:
    <<: *node
    hostname: node3
